## Testing

on: ["push"]
jobs:
  testing:
    strategy:
      matrix:
        branchname: ["staging"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.ref == format('refs/heads/{0}', matrix.branchname) }}
        
