## Testing

on: ["push"]
jobs:
  testing:
    strategy:
      matrix:
        branchname: ["staging"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: github.ref == refs/heads/${{ matrix.branchname }}
      - name: get matrix name ${{ matrix.branchname }}
        if: github.ref == refs/heads/${{ matrix.branchname }}
      - name: get ref name ${{ github.ref }}
        if: github.ref == refs/heads/${{ matrix.branchname }}
        
